/*2)WRITE A JAVA PROGRAM THAT 
READS A FLOATING-POINT NUMBER AND 
PRINTS “ZERO” IF THE NUMBER IS ZERO.
OTHERWISE, PRINT “POSITIVE” OR “NEGATIVE”. 
ADD “SMALL” IF THE ABSOLUTE VALUE OF THE NUMBER IS LESS THAN 1, 
OR “LARGE” IF IT  EXCEEDS 1,000,000
*/
import java.util.Scanner;

public class Assign13_2 {
	public static void main (String[] args) {



